# Generated by Django 4.1.5 on 2023-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='carType',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Station Wagon', 'Station Wagon'), ('Pickup Truck', 'Pickup Truck')], default=None, max_length=20, null=True),
        ),
    ]
