# Generated by Django 4.1.5 on 2023-02-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='carType',
            field=models.CharField(default='Not specify', max_length=20),
        ),
    ]
