# Generated by Django 4.1.5 on 2023-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_ride_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
