# Generated by Django 4.1.5 on 2023-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='shared',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
