# Generated by Django 4.1.5 on 2023-02-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_ride_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='totalPassNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
