# Generated by Django 4.1.5 on 2023-02-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_ride_totalpassnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='carType',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
