# Generated by Django 4.1.5 on 2023-01-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('is_driver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rideSharing.user')),
                ('vehicle_type', models.CharField(max_length=10)),
                ('license_plate_num', models.CharField(max_length=8)),
                ('special_info', models.TextField()),
                ('max_passenger', models.IntegerField()),
            ],
            bases=('rideSharing.user',),
        ),
    ]
