# Generated by Django 4.1.5 on 2023-02-02 19:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_driver', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Station Wagon', 'Station Wagon'), ('Pickup Truck', 'Pickup Truck')], default=None, max_length=20, null=True)),
                ('license_plate_nums', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('special_info', models.TextField(blank=True, default=None, null=True)),
                ('max_passenger', models.IntegerField(blank=True, default=None, null=True)),
                ('ride_list', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
