# Generated by Django 4.1.5 on 2023-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('is_driver', models.BooleanField()),
                ('vehicle_type', models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Station Wagon', 'Station Wagon'), ('Pickup Truck', 'Pickup Truck')], default=None, max_length=20, null=True)),
                ('license_plate_nums', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('special_info', models.TextField(blank=True, default=None, null=True)),
                ('max_passenger', models.IntegerField(blank=True, default=None, null=True)),
                ('ride_list', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
