# Generated by Django 4.1.5 on 2023-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='realName',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='ride_list',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
