# Generated by Django 4.1.5 on 2023-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ride_list',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_plate_nums',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_passenger',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
